<?php
/**
 * ActivityLogsApi
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cloud Storage
 *
 * Cloud Storage
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@example.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * ActivityLogsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ActivityLogsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation activityLogsList
     *
     * Activity logs list
     *
     * @param  string $author Filter by author (optional)
     * @param  \DateTime $created_at_system__before Filter by created_at_system (optional)
     * @param  \DateTime $created_at_system__after Filter by created_at_system (optional)
     * @param  \DateTime $created_at_user__before Filter by created_at_user (optional)
     * @param  \DateTime $created_at_user__after Filter by created_at_user (optional)
     * @param  int $page Page number (optional)
     * @param  int $per_page Per page row count (optional)
     * @param  int $level log level (optional)
     * @param  string $message log message (optional)
     * @param  string $object object (optional)
     * @param  string $subject log subject (optional)
     * @param  string $action log action (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ActivityLog[]|\OpenAPI\Client\Model\Error
     */
    public function activityLogsList($author = null, $created_at_system__before = null, $created_at_system__after = null, $created_at_user__before = null, $created_at_user__after = null, $page = null, $per_page = null, $level = null, $message = null, $object = null, $subject = null, $action = null)
    {
        list($response) = $this->activityLogsListWithHttpInfo($author, $created_at_system__before, $created_at_system__after, $created_at_user__before, $created_at_user__after, $page, $per_page, $level, $message, $object, $subject, $action);
        return $response;
    }

    /**
     * Operation activityLogsListWithHttpInfo
     *
     * Activity logs list
     *
     * @param  string $author Filter by author (optional)
     * @param  \DateTime $created_at_system__before Filter by created_at_system (optional)
     * @param  \DateTime $created_at_system__after Filter by created_at_system (optional)
     * @param  \DateTime $created_at_user__before Filter by created_at_user (optional)
     * @param  \DateTime $created_at_user__after Filter by created_at_user (optional)
     * @param  int $page Page number (optional)
     * @param  int $per_page Per page row count (optional)
     * @param  int $level log level (optional)
     * @param  string $message log message (optional)
     * @param  string $object object (optional)
     * @param  string $subject log subject (optional)
     * @param  string $action log action (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ActivityLog[]|\OpenAPI\Client\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function activityLogsListWithHttpInfo($author = null, $created_at_system__before = null, $created_at_system__after = null, $created_at_user__before = null, $created_at_user__after = null, $page = null, $per_page = null, $level = null, $message = null, $object = null, $subject = null, $action = null)
    {
        $request = $this->activityLogsListRequest($author, $created_at_system__before, $created_at_system__after, $created_at_user__before, $created_at_user__after, $page, $per_page, $level, $message, $object, $subject, $action);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ActivityLog[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ActivityLog[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\OpenAPI\Client\Model\Error' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ActivityLog[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ActivityLog[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation activityLogsListAsync
     *
     * Activity logs list
     *
     * @param  string $author Filter by author (optional)
     * @param  \DateTime $created_at_system__before Filter by created_at_system (optional)
     * @param  \DateTime $created_at_system__after Filter by created_at_system (optional)
     * @param  \DateTime $created_at_user__before Filter by created_at_user (optional)
     * @param  \DateTime $created_at_user__after Filter by created_at_user (optional)
     * @param  int $page Page number (optional)
     * @param  int $per_page Per page row count (optional)
     * @param  int $level log level (optional)
     * @param  string $message log message (optional)
     * @param  string $object object (optional)
     * @param  string $subject log subject (optional)
     * @param  string $action log action (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function activityLogsListAsync($author = null, $created_at_system__before = null, $created_at_system__after = null, $created_at_user__before = null, $created_at_user__after = null, $page = null, $per_page = null, $level = null, $message = null, $object = null, $subject = null, $action = null)
    {
        return $this->activityLogsListAsyncWithHttpInfo($author, $created_at_system__before, $created_at_system__after, $created_at_user__before, $created_at_user__after, $page, $per_page, $level, $message, $object, $subject, $action)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation activityLogsListAsyncWithHttpInfo
     *
     * Activity logs list
     *
     * @param  string $author Filter by author (optional)
     * @param  \DateTime $created_at_system__before Filter by created_at_system (optional)
     * @param  \DateTime $created_at_system__after Filter by created_at_system (optional)
     * @param  \DateTime $created_at_user__before Filter by created_at_user (optional)
     * @param  \DateTime $created_at_user__after Filter by created_at_user (optional)
     * @param  int $page Page number (optional)
     * @param  int $per_page Per page row count (optional)
     * @param  int $level log level (optional)
     * @param  string $message log message (optional)
     * @param  string $object object (optional)
     * @param  string $subject log subject (optional)
     * @param  string $action log action (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function activityLogsListAsyncWithHttpInfo($author = null, $created_at_system__before = null, $created_at_system__after = null, $created_at_user__before = null, $created_at_user__after = null, $page = null, $per_page = null, $level = null, $message = null, $object = null, $subject = null, $action = null)
    {
        $returnType = '\OpenAPI\Client\Model\ActivityLog[]';
        $request = $this->activityLogsListRequest($author, $created_at_system__before, $created_at_system__after, $created_at_user__before, $created_at_user__after, $page, $per_page, $level, $message, $object, $subject, $action);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'activityLogsList'
     *
     * @param  string $author Filter by author (optional)
     * @param  \DateTime $created_at_system__before Filter by created_at_system (optional)
     * @param  \DateTime $created_at_system__after Filter by created_at_system (optional)
     * @param  \DateTime $created_at_user__before Filter by created_at_user (optional)
     * @param  \DateTime $created_at_user__after Filter by created_at_user (optional)
     * @param  int $page Page number (optional)
     * @param  int $per_page Per page row count (optional)
     * @param  int $level log level (optional)
     * @param  string $message log message (optional)
     * @param  string $object object (optional)
     * @param  string $subject log subject (optional)
     * @param  string $action log action (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function activityLogsListRequest($author = null, $created_at_system__before = null, $created_at_system__after = null, $created_at_user__before = null, $created_at_user__after = null, $page = null, $per_page = null, $level = null, $message = null, $object = null, $subject = null, $action = null)
    {

        $resourcePath = '/activity-logs/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($author)) {
            $author = ObjectSerializer::serializeCollection($author, '', true);
        }
        if ($author !== null) {
            $queryParams['author'] = $author;
        }
        // query params
        if (is_array($created_at_system__before)) {
            $created_at_system__before = ObjectSerializer::serializeCollection($created_at_system__before, '', true);
        }
        if ($created_at_system__before !== null) {
            $queryParams['created_at_system__before'] = $created_at_system__before;
        }
        // query params
        if (is_array($created_at_system__after)) {
            $created_at_system__after = ObjectSerializer::serializeCollection($created_at_system__after, '', true);
        }
        if ($created_at_system__after !== null) {
            $queryParams['created_at_system__after'] = $created_at_system__after;
        }
        // query params
        if (is_array($created_at_user__before)) {
            $created_at_user__before = ObjectSerializer::serializeCollection($created_at_user__before, '', true);
        }
        if ($created_at_user__before !== null) {
            $queryParams['created_at_user__before'] = $created_at_user__before;
        }
        // query params
        if (is_array($created_at_user__after)) {
            $created_at_user__after = ObjectSerializer::serializeCollection($created_at_user__after, '', true);
        }
        if ($created_at_user__after !== null) {
            $queryParams['created_at_user__after'] = $created_at_user__after;
        }
        // query params
        if (is_array($page)) {
            $page = ObjectSerializer::serializeCollection($page, '', true);
        }
        if ($page !== null) {
            $queryParams['page'] = $page;
        }
        // query params
        if (is_array($per_page)) {
            $per_page = ObjectSerializer::serializeCollection($per_page, '', true);
        }
        if ($per_page !== null) {
            $queryParams['per_page'] = $per_page;
        }
        // query params
        if (is_array($level)) {
            $level = ObjectSerializer::serializeCollection($level, '', true);
        }
        if ($level !== null) {
            $queryParams['level'] = $level;
        }
        // query params
        if (is_array($message)) {
            $message = ObjectSerializer::serializeCollection($message, '', true);
        }
        if ($message !== null) {
            $queryParams['message'] = $message;
        }
        // query params
        if (is_array($object)) {
            $object = ObjectSerializer::serializeCollection($object, '', true);
        }
        if ($object !== null) {
            $queryParams['object'] = $object;
        }
        // query params
        if (is_array($subject)) {
            $subject = ObjectSerializer::serializeCollection($subject, '', true);
        }
        if ($subject !== null) {
            $queryParams['subject'] = $subject;
        }
        // query params
        if (is_array($action)) {
            $action = ObjectSerializer::serializeCollection($action, '', true);
        }
        if ($action !== null) {
            $queryParams['action'] = $action;
        }



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createActivityLog
     *
     * Create activity log
     *
     * @param  \OpenAPI\Client\Model\ActivityLog $body activity log data (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ActivityLog|\OpenAPI\Client\Model\Error
     */
    public function createActivityLog($body)
    {
        list($response) = $this->createActivityLogWithHttpInfo($body);
        return $response;
    }

    /**
     * Operation createActivityLogWithHttpInfo
     *
     * Create activity log
     *
     * @param  \OpenAPI\Client\Model\ActivityLog $body activity log data (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ActivityLog|\OpenAPI\Client\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function createActivityLogWithHttpInfo($body)
    {
        $request = $this->createActivityLogRequest($body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 201:
                    if ('\OpenAPI\Client\Model\ActivityLog' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ActivityLog', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if ('\OpenAPI\Client\Model\Error' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ActivityLog';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ActivityLog',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createActivityLogAsync
     *
     * Create activity log
     *
     * @param  \OpenAPI\Client\Model\ActivityLog $body activity log data (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createActivityLogAsync($body)
    {
        return $this->createActivityLogAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createActivityLogAsyncWithHttpInfo
     *
     * Create activity log
     *
     * @param  \OpenAPI\Client\Model\ActivityLog $body activity log data (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createActivityLogAsyncWithHttpInfo($body)
    {
        $returnType = '\OpenAPI\Client\Model\ActivityLog';
        $request = $this->createActivityLogRequest($body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createActivityLog'
     *
     * @param  \OpenAPI\Client\Model\ActivityLog $body activity log data (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createActivityLogRequest($body)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling createActivityLog'
            );
        }

        $resourcePath = '/activity-logs/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
