<?php
/**
 * FilesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Cloud Storage
 *
 * Cloud Storage
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@example.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FilesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for callList
     *
     * Files list.
     *
     */
    public function testCallList()
    {
    }

    /**
     * Test case for completeMultipartUpload
     *
     * Complete multipart upload.
     *
     */
    public function testCompleteMultipartUpload()
    {
    }

    /**
     * Test case for create
     *
     * Create file.
     *
     */
    public function testCreate()
    {
    }

    /**
     * Test case for delete
     *
     * Delete file.
     *
     */
    public function testDelete()
    {
    }

    /**
     * Test case for get
     *
     * Get file.
     *
     */
    public function testGet()
    {
    }

    /**
     * Test case for getFileInfo
     *
     * Get file's info.
     *
     */
    public function testGetFileInfo()
    {
    }

    /**
     * Test case for updateMeta
     *
     * Update file's meta.
     *
     */
    public function testUpdateMeta()
    {
    }

    /**
     * Test case for uploadContent
     *
     * Upload content.
     *
     */
    public function testUploadContent()
    {
    }
}
